software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  etcdctl:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    start_in: "etcd"
    packages:
      - type: debian
        name: etcdctl
        repos:
          - mxm-public
        target: install
